### ISSUE TITLE
Other versions support?

### ISSUE THREAD

**Issue by zientix** [lumien231/Chunk-Animator#13]
Are you planning to support 1.14, 1.15 and 1.16 in future?

**Comment by koderian** [comment]
Want to know as well

**Comment by zientix** [comment]
Actually maybe I will try to revive this thing for Fabric, but I don't promise anything

**Comment by TheKodeToad** [comment]
There is an existing Fabric mod: https://github.com/fl0gic/smooth-chunks.

**Comment by zientix** [comment]
Oh, thanks!

**Comment by koderian** [comment]
Is there a possibility of a revival for Forge 1.16.X?

**Comment by Harleyoc1** [comment]
@koderian #14
