### ISSUE TITLE
Crash when I try to join a server

### ISSUE THREAD

**Issue by jules552** [lumien231/Chunk-Animator#4]
Hey,

I have the last version of Chunk Animator in 1.11, with the last version of Forge, my minecraft client crash when I'm tring to join a server (I haven't test to join a solo world). 

You can check my crash-report:
http://pastebin.com/ZD5s1fDj

Can you fix this problem ?
Thank you for your work and have a nice day!

**Comment by lumien231** [comment]
Can you reproduce this without other mods installed?

**Comment by jules552** [comment]
With just ChunkAnimator there is no crash

**Comment by lumien231** [comment]
Could you maybe find out with which mod it conflicts? (Remove half, check whether it still crashes -> repeat)

**Comment by jules552** [comment]
I will try to delete mods one by one but it will take a lot of time, when I have the result I will communicate it

**Comment by lumien231** [comment]
Again you can just remove HALF at a time and then check whether it still crashes. Should not take too long then.

**Comment by jules552** [comment]
Excuse me, I don't have the time to check during this days because of the Xmas festivity etc.. and I haven't my computer, I will test that tomorrow  ;)
