### ISSUE TITLE
Optifine incompatibility

### ISSUE THREAD

**Issue by Szasdragon** [lumien231/Chunk-Animator#6]
MC 1.12.2
Optifine 1.12.2 HD U D2
Chunk animation not working.
Tried many tweaks, but the one solution which worked, is disabling Optifine.

**Comment by JohnLouderback** [comment]
Any fix for this?

**Comment by naqaden** [comment]
I missed the D2 version, updating from Optifine 1.12.2 HD U D1 to D3 and haven't had any trouble.

**Comment by Alaberti** [comment]
Probably need to report to optifine

**Comment by jtx46** [comment]
works on Optifine. I just had to Edit some of Optifines Performance Settings. in the newer Versions there's settings like Smart Animations that i think was the main Culprit. how many other settings you have to tweak depends on how many Optifine Settings uve changed or the Lack there of. (I'm to lazy to look up the Specifics as I'm dealing with Phosphor Incompatibilities atm on my 127 modded server.....more Fun)

**Comment by AWSMcube** [comment]
Solution for 1.8.9 with Optifine:
Options > Video Settings > Performance > Render regions: OFF
